#! /bin/bash
#
#     Copyright (C) 2017 Intel Corporation
#
#     Redistribution and use in source and binary forms, with or
#     without modification, are permitted provided that the following
#     conditions are met:
#
#     1. Redistributions of source code must retain the above
#        copyright notice, this list of conditions and the following
#        disclaimer.
#     2. Redistributions in binary form must reproduce the above
#        copyright notice, this list of conditions and the following
#        disclaimer in the documentation and/or other materials
#        provided with the distribution.
#
#     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
#     CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
#     INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#     MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
#     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
#     CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#     SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
#     NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
#     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
#     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#     CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#     OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
#     EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

_this_script=$(cd ${0%[\\/]*} && echo $(pwd 2>/dev/null)/${0##*/})
_this_dir=$(dirname ${_this_script})

SCRIPT_NAME="$(basename ${_this_script})"
set -e
RBF=""
PCIE_CARD=""
REGION=""
function usage()
{
	echo
	echo "Usage:" 
	echo "-f=, --file="
	echo "rbf:   path to rbf file to load"
	echo "-d=, --device="
	echo "Device:  pci id for card to load (e.g. 0000:03:00.0)"
	echo "-r=, --region="
	echo "Region: offset for the target region controller, unsigned integer"
	echo "(e.g $SCRIPT_NAME -f=<rbf> --device=0000:03:00.0 -r=100)" 
	echo
	exit 1
}

for i in "$@"
do
case $i in
	--file=*|-f=*)
	RBF="${i#*=}"
	echo "RBF is $RBF" 
	;;
	-d=*|--device=*)
	PCIE_CARD="${i#*=}"
	echo "PCIe device is $PCIE_CARD"
	;;
	-r=*|--region=*)
	REGION="${i#*=}"
	echo "Region offset is 0x$REGION"
	;;
	-h|--help=*)
	echo "Printing usage"
	usage
	;;
	*)
	echo "Error in parameters"
	usage
	;;
esac
done

if [ -z "$REGION" ]
then
	echo
	echo "ERROR! No Region offset specified"
	usage
fi
if [ -z "$RBF" ]
then
	echo 
	echo "ERROR! No rbf specified."
	usage
fi

if  [  ! -e $RBF  ]
then
	echo
	echo "ERROR! rbf specified does not exist."
	usage
fi

if [ -z "$PCIE_CARD" ]
then
	echo
	echo "ERROR! No PCIe device specified using the -d= or --device= option"
	usage
fi

FPGA_MGR=/sys/kernel/debug/fpga_manager/$PCIE_CARD
STATE=/sys/kernel/debug/fpga_pcie/$PCIE_CARD/state

if [ -e $STATE ]
then
	echo "found $STATE"
else
	echo "cannot find $STATE"
	exit 1
fi

# probe pr ip and pr controller
echo 3 > $STATE 2> /dev/null
if [ $? != 0 ]
then
	echo "could not probe PR components"
	exit 1
fi

if [ -e $FPGA_MGR ]
then
	echo "found fpga manager for $PCIE_CARD"
else
	echo "cannot find fpga manager for $PCIE_CARD"
	exit 1
fi


cp $RBF /lib/firmware
FW=$(basename $RBF)

echo 1 > $FPGA_MGR/flags
echo 10 > $FPGA_MGR/config_to

$_this_dir/fpga_region_controller $PCIE_CARD enable $REGION

echo $FW > $FPGA_MGR/firmware_name

if [ $? != "0" ]
then
	echo
	echo "Partial Reconfigured FAILED"
	exit 1
fi

$_this_dir/fpga_region_controller $PCIE_CARD disable $REGION
echo 3 > $STATE 2> /dev/null